/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Resume = {
  _id: string;
  _type: "resume";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  resumeFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  version?: string;
  isActive?: boolean;
  description?: string;
  uploadDate?: string;
  previewImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
  icon?: string;
  isExternal?: boolean;
  order?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteKeywords?: Array<string>;
  siteLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  ctaText?: string;
  ctaUrl?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroBackground?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  showBlog?: boolean;
  showServices?: boolean;
  showTestimonials?: boolean;
  googleAnalyticsId?: string;
  facebookPixelId?: string;
  twitterHandle?: string;
  footer?: {
    text?: string;
    copyrightText?: string;
    links?: Array<{
      title?: string;
      url?: string;
      _key: string;
    }>;
  };
  trustLogos?: Array<{
    name?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    url?: string;
    _key: string;
  }>;
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
};

export type Uses = {
  _id: string;
  _type: "uses";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categories?: Array<{
    label?: string;
    value?: string;
    _type: "category";
    _key: string;
  }>;
};

export type Now = {
  _id: string;
  _type: "now";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  month?: string;
  items?: Array<string>;
  reading?: string;
};

export type Decision = {
  _id: string;
  _type: "decision";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  status?: "proposed" | "accepted" | "deprecated" | "superseded";
  impact?: "S" | "M" | "L";
  domain?: string;
  supersededBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "decision";
  };
  summary?: string;
  context?: string;
  optionsConsidered?: Array<{
    label?: string;
    summary?: string;
    _type: "option";
    _key: string;
  }>;
  decision?: string;
  tradeoffs?: string;
  revisitTrigger?: string;
  takeaways?: Array<string>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    language?: "ts" | "tsx" | "js" | "jsx" | "go" | "rust" | "py" | "sh" | "sql" | "json" | "yaml" | "java" | "kotlin" | "swift" | "text";
    code?: string;
    caption?: string;
    _type: "codeBlock";
    _key: string;
  }>;
  relatedProjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  tags?: Array<string>;
  published?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "archived";
  notes?: string;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription?: string;
  fullDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  features?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  deliverables?: Array<string>;
  pricing?: {
    startingPrice?: number;
    priceType?: "hourly" | "project" | "monthly" | "custom";
    description?: string;
  };
  timeline?: string;
  featured?: boolean;
  order?: number;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: "tutorial" | "technical" | "ai-ml" | "web-dev" | "career" | "opinion" | "showcase" | "best-practices" | "news";
  tags?: Array<string>;
  publishedAt?: string;
  readTime?: number;
};

export type Achievement = {
  _id: string;
  _type: "achievement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  type?: "award" | "hackathon" | "publication" | "speaking" | "open-source" | "milestone" | "recognition" | "other";
  issuer?: string;
  date?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  featured?: boolean;
  order?: number;
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  issuer?: string;
  issueDate?: string;
  expiryDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  company?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  testimonial?: string;
  rating?: number;
  date?: string;
  linkedinUrl?: string;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  featured?: boolean;
  order?: number;
};

export type Education = {
  _id: string;
  _type: "education";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  institution?: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  gpa?: string;
  description?: string;
  achievements?: Array<string>;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  position?: string;
  employmentType?: "full-time" | "part-time" | "contract" | "freelance" | "internship";
  location?: string;
  startDate?: string;
  endDate?: string;
  current?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  responsibilities?: Array<string>;
  achievements?: Array<string>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  companyWebsite?: string;
  order?: number;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "frontend" | "backend" | "ai-ml" | "devops" | "database" | "mobile" | "cloud" | "testing" | "design" | "tools" | "soft-skills" | "other";
  proficiency?: "beginner" | "intermediate" | "advanced" | "expert";
  yearsOfExperience?: number;
  color?: string;
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  headline?: string;
  headlineStaticText?: string;
  headlineAnimatedWords?: Array<string>;
  headlineAnimationDuration?: number;
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  quote?: string;
  quoteContext?: string;
  profileImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  email?: string;
  phone?: string;
  location?: string;
  calLink?: string;
  availability?: "available" | "open" | "unavailable";
  socialLinks?: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  };
  yearsOfExperience?: number;
  stats?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  tagline?: string;
  metrics?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skill";
  }>;
  category?: "web-app" | "mobile-app" | "ai-ml" | "api-backend" | "devops" | "open-source" | "cli-tool" | "desktop-app" | "browser-extension" | "game" | "other";
  liveUrl?: string;
  githubUrl?: string;
  featured?: boolean;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Resume | SanityImageCrop | SanityImageHotspot | Navigation | SiteSettings | Uses | Now | Decision | Slug | Contact | Service | Blog | Achievement | Certification | Testimonial | Education | Experience | Skill | Profile | Project | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/(portfolio)/decisions/[slug]/page.tsx
// Variable: DECISION_QUERY
// Query: *[_type == "decision" && slug.current == $slug && published == true][0] {    "slug": slug.current,    title,    date,    status,    impact,    domain,    summary,    context,    optionsConsidered[] {      label,      summary    },    decision,    tradeoffs,    revisitTrigger,    takeaways,    body,    tags,    "supersededBy": supersededBy->{      "slug": slug.current,      title    },    "relatedProjects": relatedProjects[]->{      "slug": slug.current,      title,      tagline    },    "adrNumber": count(*[_type == "decision" && published == true && date <= ^.date])  }
export type DECISION_QUERYResult = {
  slug: string | null;
  title: string | null;
  date: string | null;
  status: "accepted" | "deprecated" | "proposed" | "superseded" | null;
  impact: "L" | "M" | "S" | null;
  domain: string | null;
  summary: string | null;
  context: string | null;
  optionsConsidered: Array<{
    label: string | null;
    summary: string | null;
  }> | null;
  decision: string | null;
  tradeoffs: string | null;
  revisitTrigger: string | null;
  takeaways: Array<string> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    language?: "go" | "java" | "js" | "json" | "jsx" | "kotlin" | "py" | "rust" | "sh" | "sql" | "swift" | "text" | "ts" | "tsx" | "yaml";
    code?: string;
    caption?: string;
    _type: "codeBlock";
    _key: string;
  }> | null;
  tags: Array<string> | null;
  supersededBy: {
    slug: string | null;
    title: string | null;
  } | null;
  relatedProjects: Array<{
    slug: string | null;
    title: string | null;
    tagline: string | null;
  }> | null;
  adrNumber: number;
} | null;

// Source: ./src/app/(portfolio)/decisions/feed.json/route.ts
// Variable: FEED_JSON_QUERY
// Query: *[_type == "decision" && published == true] | order(date desc)[0...50] {    "slug": slug.current,    title,    date,    summary,    status,    impact,    domain,    tags  }
export type FEED_JSON_QUERYResult = Array<{
  slug: string | null;
  title: string | null;
  date: string | null;
  summary: string | null;
  status: "accepted" | "deprecated" | "proposed" | "superseded" | null;
  impact: "L" | "M" | "S" | null;
  domain: string | null;
  tags: Array<string> | null;
}>;

// Source: ./src/app/(portfolio)/decisions/feed.xml/route.ts
// Variable: FEED_QUERY
// Query: *[_type == "decision" && published == true] | order(date desc)[0...30] {    "slug": slug.current,    title,    date,    summary,    status  }
export type FEED_QUERYResult = Array<{
  slug: string | null;
  title: string | null;
  date: string | null;
  summary: string | null;
  status: "accepted" | "deprecated" | "proposed" | "superseded" | null;
}>;

// Source: ./src/app/(portfolio)/decisions/page.tsx
// Variable: DECISIONS_QUERY
// Query: *[_type == "decision" && published == true] | order(date asc) {    "slug": slug.current,    title,    date,    summary,    status,    impact,    domain,    tags  }
export type DECISIONS_QUERYResult = Array<{
  slug: string | null;
  title: string | null;
  date: string | null;
  summary: string | null;
  status: "accepted" | "deprecated" | "proposed" | "superseded" | null;
  impact: "L" | "M" | "S" | null;
  domain: string | null;
  tags: Array<string> | null;
}>;

// Source: ./src/app/v2/page.tsx
// Variable: V2_PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0] {  firstName,  lastName,  headline,  shortBio,  location,  yearsOfExperience,  email,  availability,  socialLinks,}
export type V2_PROFILE_QUERYResult = {
  firstName: null;
  lastName: null;
  headline: null;
  shortBio: null;
  location: null;
  yearsOfExperience: null;
  email: null;
  availability: null;
  socialLinks: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  shortBio: null;
  location: null;
  yearsOfExperience: number | null;
  email: null;
  availability: null;
  socialLinks: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  shortBio: null;
  location: string | null;
  yearsOfExperience: null;
  email: null;
  availability: null;
  socialLinks: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  shortBio: null;
  location: null;
  yearsOfExperience: null;
  email: string | null;
  availability: null;
  socialLinks: null;
} | {
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  shortBio: string | null;
  location: string | null;
  yearsOfExperience: number | null;
  email: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  } | null;
} | null;
// Variable: V2_PROJECTS_QUERY
// Query: *[_type == "project"] | order(featured desc, _createdAt desc)[0...8] {  title,  tagline,  metrics,  liveUrl,  githubUrl,  "stack": technologies[]->name}
export type V2_PROJECTS_QUERYResult = Array<{
  title: string | null;
  tagline: string | null;
  metrics: string | null;
  liveUrl: string | null;
  githubUrl: string | null;
  stack: Array<string | null> | null;
}>;
// Variable: V2_EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc)[0...5] {  jobTitle,  company,  startDate,  endDate,  current,  achievements}
export type V2_EXPERIENCE_QUERYResult = Array<{
  jobTitle: null;
  company: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  achievements: Array<string> | null;
}>;
// Variable: V2_DECISIONS_QUERY
// Query: *[_type == "decision" && published == true] | order(date desc)[0...12] {  "slug": slug.current,  title,  date,  summary,  status}
export type V2_DECISIONS_QUERYResult = Array<{
  slug: string | null;
  title: string | null;
  date: string | null;
  summary: string | null;
  status: "accepted" | "deprecated" | "proposed" | "superseded" | null;
}>;
// Variable: NOW_QUERY
// Query: *[_id == "singleton-now"][0] {  month,  items,  reading}
export type NOW_QUERYResult = {
  month: null;
  items: null;
  reading: null;
} | {
  month: string | null;
  items: Array<string> | null;
  reading: string | null;
} | null;
// Variable: USES_QUERY
// Query: *[_id == "singleton-uses"][0] {  categories}
export type USES_QUERYResult = {
  categories: null;
} | {
  categories: Array<{
    label?: string;
    value?: string;
    _type: "category";
    _key: string;
  }> | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "singleton-siteSettings"][0] {  trustLogos[] {    name,    url,    "logoAlt": logo.alt  }}
export type SITE_SETTINGS_QUERYResult = {
  trustLogos: null;
} | {
  trustLogos: Array<{
    name: string | null;
    url: string | null;
    logoAlt: string | null;
  }> | null;
} | null;

// Source: ./src/components/FloatingDock.tsx
// Variable: DOCK_DATA_QUERY
// Query: {  "navItems": *[_type == "navigation"] | order(order asc){    title,    href,    icon,    isExternal  },  "calLink": *[_id == "singleton-profile"][0].calLink}
export type DOCK_DATA_QUERYResult = {
  navItems: Array<{
    title: string | null;
    href: string | null;
    icon: string | null;
    isExternal: boolean | null;
  }>;
  calLink: null | string;
};

// Source: ./src/components/chat/ChatWrapper.tsx
// Variable: CHAT_PROFILE_QUERY
// Query: {    "profile": *[_id == "singleton-profile"][0]{      firstName,      lastName,      headline,      shortBio,      fullBio,      email,      phone,      location,      availability,      socialLinks,      yearsOfExperience,      stats    },    "experience": *[_type == "experience"] | order(startDate desc){      _id,      jobTitle,      company,      location,      startDate,      endDate,      current,      description,      achievements[],      technologies[]->{name, category}    },    "projects": *[_type == "project"] | order(order asc){      _id,      title,      tagline,      category,      liveUrl,      githubUrl,      technologies[]->{name, category}    },    "skills": *[_type == "skill"] | order(name asc){      _id,      name,      category,      level,      yearsOfExperience,      percentage    },    "education": *[_type == "education"] | order(endDate desc){      _id,      degree,      field,      institution,      location,      startDate,      endDate,      description,      gpa    }  }
export type CHAT_PROFILE_QUERYResult = {
  profile: {
    firstName: null;
    lastName: null;
    headline: null;
    shortBio: null;
    fullBio: null;
    email: null;
    phone: null;
    location: null;
    availability: null;
    socialLinks: null;
    yearsOfExperience: null;
    stats: null;
  } | {
    firstName: null;
    lastName: null;
    headline: null;
    shortBio: null;
    fullBio: null;
    email: null;
    phone: null;
    location: null;
    availability: null;
    socialLinks: null;
    yearsOfExperience: number | null;
    stats: null;
  } | {
    firstName: null;
    lastName: null;
    headline: null;
    shortBio: null;
    fullBio: null;
    email: null;
    phone: null;
    location: string | null;
    availability: null;
    socialLinks: null;
    yearsOfExperience: null;
    stats: null;
  } | {
    firstName: null;
    lastName: null;
    headline: null;
    shortBio: null;
    fullBio: null;
    email: string | null;
    phone: null;
    location: null;
    availability: null;
    socialLinks: null;
    yearsOfExperience: null;
    stats: null;
  } | {
    firstName: string | null;
    lastName: string | null;
    headline: string | null;
    shortBio: string | null;
    fullBio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    email: string | null;
    phone: string | null;
    location: string | null;
    availability: "available" | "open" | "unavailable" | null;
    socialLinks: {
      github?: string;
      linkedin?: string;
      twitter?: string;
      website?: string;
      medium?: string;
      devto?: string;
      youtube?: string;
      stackoverflow?: string;
    } | null;
    yearsOfExperience: number | null;
    stats: Array<{
      label?: string;
      value?: string;
      _key: string;
    }> | null;
  } | null;
  experience: Array<{
    _id: string;
    jobTitle: null;
    company: string | null;
    location: string | null;
    startDate: string | null;
    endDate: string | null;
    current: boolean | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    achievements: Array<string> | null;
    technologies: Array<{
      name: string | null;
      category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    }> | null;
  }>;
  projects: Array<{
    _id: string;
    title: string | null;
    tagline: string | null;
    category: "ai-ml" | "api-backend" | "browser-extension" | "cli-tool" | "desktop-app" | "devops" | "game" | "mobile-app" | "open-source" | "other" | "web-app" | null;
    liveUrl: string | null;
    githubUrl: string | null;
    technologies: Array<{
      name: string | null;
      category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    }> | null;
  }>;
  skills: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    level: null;
    yearsOfExperience: number | null;
    percentage: null;
  }>;
  education: Array<{
    _id: string;
    degree: string | null;
    field: null;
    institution: string | null;
    location: null;
    startDate: string | null;
    endDate: string | null;
    description: string | null;
    gpa: string | null;
  }>;
};

// Source: ./src/components/sections/AboutSection.tsx
// Variable: ABOUT_QUERY
// Query: *[_id == "singleton-profile"][0]{  firstName,  lastName,  fullBio,  quote,  quoteContext,  yearsOfExperience,  stats,  email,  phone,  location}
export type ABOUT_QUERYResult = {
  firstName: null;
  lastName: null;
  fullBio: null;
  quote: null;
  quoteContext: null;
  yearsOfExperience: null;
  stats: null;
  email: null;
  phone: null;
  location: null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  quote: null;
  quoteContext: null;
  yearsOfExperience: number | null;
  stats: null;
  email: null;
  phone: null;
  location: null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  quote: null;
  quoteContext: null;
  yearsOfExperience: null;
  stats: null;
  email: null;
  phone: null;
  location: string | null;
} | {
  firstName: null;
  lastName: null;
  fullBio: null;
  quote: null;
  quoteContext: null;
  yearsOfExperience: null;
  stats: null;
  email: string | null;
  phone: null;
  location: null;
} | {
  firstName: string | null;
  lastName: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  quote: string | null;
  quoteContext: string | null;
  yearsOfExperience: number | null;
  stats: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
  email: string | null;
  phone: string | null;
  location: string | null;
} | null;

// Source: ./src/components/sections/AchievementsSection.tsx
// Variable: ACHIEVEMENTS_QUERY
// Query: *[_type == "achievement"] | order(date desc){  title,  type,  issuer,  date,  description,  image,  url,  featured,  order}
export type ACHIEVEMENTS_QUERYResult = Array<{
  title: string | null;
  type: "award" | "hackathon" | "milestone" | "open-source" | "other" | "publication" | "recognition" | "speaking" | null;
  issuer: string | null;
  date: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  url: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./src/components/sections/BlogSection.tsx
// Variable: BLOG_QUERY
// Query: *[_type == "blog"] | order(publishedAt desc){  title,  slug,  excerpt,  category,  tags,  publishedAt,  readTime,  featuredImage}
export type BLOG_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  category: "ai-ml" | "best-practices" | "career" | "news" | "opinion" | "showcase" | "technical" | "tutorial" | "web-dev" | null;
  tags: Array<string> | null;
  publishedAt: string | null;
  readTime: number | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ./src/components/sections/CertificationsSection.tsx
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"] | order(issueDate desc){  name,  issuer,  issueDate,  expiryDate,  credentialId,  credentialUrl,  logo,  description,  skills[]->{name, category},  order}
export type CERTIFICATIONS_QUERYResult = Array<{
  name: string | null;
  issuer: string | null;
  issueDate: string | null;
  expiryDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  skills: Array<{
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  }> | null;
  order: number | null;
}>;

// Source: ./src/components/sections/ContactSection.tsx
// Variable: PROFILE_QUERY
// Query: *[_id == "singleton-profile"][0]{  email,  phone,  location,  socialLinks,  calLink}
export type PROFILE_QUERYResult = {
  email: null;
  phone: null;
  location: null;
  socialLinks: null;
  calLink: null;
} | {
  email: null;
  phone: null;
  location: string | null;
  socialLinks: null;
  calLink: null;
} | {
  email: string | null;
  phone: null;
  location: null;
  socialLinks: null;
  calLink: null;
} | {
  email: string | null;
  phone: string | null;
  location: string | null;
  socialLinks: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  } | null;
  calLink: string | null;
} | null;

// Source: ./src/components/sections/EducationSection.tsx
// Variable: EDUCATION_QUERY
// Query: *[_type == "education"] | order(endDate desc, startDate desc){  institution,  degree,  fieldOfStudy,  startDate,  endDate,  current,  gpa,  description,  achievements,  logo,  website,  order}
export type EDUCATION_QUERYResult = Array<{
  institution: string | null;
  degree: string | null;
  fieldOfStudy: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  gpa: string | null;
  description: string | null;
  achievements: Array<string> | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  website: string | null;
  order: number | null;
}>;

// Source: ./src/components/sections/ExperienceSection.tsx
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"] | order(startDate desc){  company,  position,  employmentType,  location,  startDate,  endDate,  current,  description,  responsibilities,  achievements,  technologies[]->{name, category},  companyLogo,  companyWebsite}
export type EXPERIENCE_QUERYResult = Array<{
  company: string | null;
  position: string | null;
  employmentType: "contract" | "freelance" | "full-time" | "internship" | "part-time" | null;
  location: string | null;
  startDate: string | null;
  endDate: string | null;
  current: boolean | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  responsibilities: Array<string> | null;
  achievements: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  }> | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyWebsite: string | null;
}>;

// Source: ./src/components/sections/HeroSection.tsx
// Variable: HERO_QUERY
// Query: *[_id== "singleton-profile"][0] {  firstName,  lastName,  headline,  headlineStaticText,  headlineAnimatedWords,  headlineAnimationDuration,  shortBio,  fullBio,  email,  phone,  location,  availability,  socialLinks,  calLink,  yearsOfExperience,  profileImage,  profileImages,}
export type HERO_QUERYResult = {
  firstName: null;
  lastName: null;
  headline: null;
  headlineStaticText: null;
  headlineAnimatedWords: null;
  headlineAnimationDuration: null;
  shortBio: null;
  fullBio: null;
  email: null;
  phone: null;
  location: null;
  availability: null;
  socialLinks: null;
  calLink: null;
  yearsOfExperience: null;
  profileImage: null;
  profileImages: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  headlineStaticText: null;
  headlineAnimatedWords: null;
  headlineAnimationDuration: null;
  shortBio: null;
  fullBio: null;
  email: null;
  phone: null;
  location: null;
  availability: null;
  socialLinks: null;
  calLink: null;
  yearsOfExperience: number | null;
  profileImage: null;
  profileImages: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  headlineStaticText: null;
  headlineAnimatedWords: null;
  headlineAnimationDuration: null;
  shortBio: null;
  fullBio: null;
  email: null;
  phone: null;
  location: string | null;
  availability: null;
  socialLinks: null;
  calLink: null;
  yearsOfExperience: null;
  profileImage: null;
  profileImages: null;
} | {
  firstName: null;
  lastName: null;
  headline: null;
  headlineStaticText: null;
  headlineAnimatedWords: null;
  headlineAnimationDuration: null;
  shortBio: null;
  fullBio: null;
  email: string | null;
  phone: null;
  location: null;
  availability: null;
  socialLinks: null;
  calLink: null;
  yearsOfExperience: null;
  profileImage: null;
  profileImages: null;
} | {
  firstName: string | null;
  lastName: string | null;
  headline: string | null;
  headlineStaticText: string | null;
  headlineAnimatedWords: Array<string> | null;
  headlineAnimationDuration: number | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  email: string | null;
  phone: string | null;
  location: string | null;
  availability: "available" | "open" | "unavailable" | null;
  socialLinks: {
    github?: string;
    linkedin?: string;
    twitter?: string;
    website?: string;
    medium?: string;
    devto?: string;
    youtube?: string;
    stackoverflow?: string;
  } | null;
  calLink: string | null;
  yearsOfExperience: number | null;
  profileImage: null;
  profileImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;
// Variable: LATEST_RESUME_QUERY
// Query: *[_type == "resume"] | order(isActive desc, uploadDate desc)[0] {  _id,  title,  resumeFile,  version,  isActive,  uploadDate}
export type LATEST_RESUME_QUERYResult = {
  _id: string;
  title: string | null;
  resumeFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  } | null;
  version: string | null;
  isActive: boolean | null;
  uploadDate: string | null;
} | null;

// Source: ./src/components/sections/ProjectsSection.tsx
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(order asc)[0...6]{  title,  slug,  tagline,  category,  liveUrl,  githubUrl,  coverImage,  technologies[]->{name, category, color}}
export type PROJECTS_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  tagline: string | null;
  category: "ai-ml" | "api-backend" | "browser-extension" | "cli-tool" | "desktop-app" | "devops" | "game" | "mobile-app" | "open-source" | "other" | "web-app" | null;
  liveUrl: string | null;
  githubUrl: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  technologies: Array<{
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
    color: string | null;
  }> | null;
}>;

// Source: ./src/components/sections/ServicesSection.tsx
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, _createdAt desc){  title,  slug,  icon,  shortDescription,  fullDescription,  features,  technologies[]->{name, category},  deliverables,  pricing,  timeline,  featured,  order}
export type SERVICES_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  icon: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  fullDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  features: Array<string> | null;
  technologies: Array<{
    name: string | null;
    category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  }> | null;
  deliverables: Array<string> | null;
  pricing: {
    startingPrice?: number;
    priceType?: "custom" | "hourly" | "monthly" | "project";
    description?: string;
  } | null;
  timeline: string | null;
  featured: boolean | null;
  order: number | null;
}>;

// Source: ./src/components/sections/SkillsSection.tsx
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(category asc, order asc){  name,  category,  proficiency,  color}
export type SKILLS_QUERYResult = Array<{
  name: string | null;
  category: "ai-ml" | "backend" | "cloud" | "database" | "design" | "devops" | "frontend" | "mobile" | "other" | "soft-skills" | "testing" | "tools" | null;
  proficiency: "advanced" | "beginner" | "expert" | "intermediate" | null;
  color: string | null;
}>;

// Source: ./src/components/sections/TestimonialsSection.tsx
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(order asc){  name,  position,  company,  testimonial,  rating,  date,  avatar,  companyLogo,  linkedinUrl}
export type TESTIMONIALS_QUERYResult = Array<{
  name: string | null;
  position: string | null;
  company: string | null;
  testimonial: string | null;
  rating: number | null;
  date: string | null;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  companyLogo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  linkedinUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"decision\" && slug.current == $slug && published == true][0] {\n    \"slug\": slug.current,\n    title,\n    date,\n    status,\n    impact,\n    domain,\n    summary,\n    context,\n    optionsConsidered[] {\n      label,\n      summary\n    },\n    decision,\n    tradeoffs,\n    revisitTrigger,\n    takeaways,\n    body,\n    tags,\n    \"supersededBy\": supersededBy->{\n      \"slug\": slug.current,\n      title\n    },\n    \"relatedProjects\": relatedProjects[]->{\n      \"slug\": slug.current,\n      title,\n      tagline\n    },\n    \"adrNumber\": count(*[_type == \"decision\" && published == true && date <= ^.date])\n  }\n": DECISION_QUERYResult;
    "\n  *[_type == \"decision\" && published == true] | order(date desc)[0...50] {\n    \"slug\": slug.current,\n    title,\n    date,\n    summary,\n    status,\n    impact,\n    domain,\n    tags\n  }\n": FEED_JSON_QUERYResult;
    "\n  *[_type == \"decision\" && published == true] | order(date desc)[0...30] {\n    \"slug\": slug.current,\n    title,\n    date,\n    summary,\n    status\n  }\n": FEED_QUERYResult;
    "\n  *[_type == \"decision\" && published == true] | order(date asc) {\n    \"slug\": slug.current,\n    title,\n    date,\n    summary,\n    status,\n    impact,\n    domain,\n    tags\n  }\n": DECISIONS_QUERYResult;
    "*[_id == \"singleton-profile\"][0] {\n  firstName,\n  lastName,\n  headline,\n  shortBio,\n  location,\n  yearsOfExperience,\n  email,\n  availability,\n  socialLinks,\n}": V2_PROFILE_QUERYResult;
    "*[_type == \"project\"] | order(featured desc, _createdAt desc)[0...8] {\n  title,\n  tagline,\n  metrics,\n  liveUrl,\n  githubUrl,\n  \"stack\": technologies[]->name\n}": V2_PROJECTS_QUERYResult;
    "*[_type == \"experience\"] | order(startDate desc)[0...5] {\n  jobTitle,\n  company,\n  startDate,\n  endDate,\n  current,\n  achievements\n}": V2_EXPERIENCE_QUERYResult;
    "*[_type == \"decision\" && published == true] | order(date desc)[0...12] {\n  \"slug\": slug.current,\n  title,\n  date,\n  summary,\n  status\n}": V2_DECISIONS_QUERYResult;
    "*[_id == \"singleton-now\"][0] {\n  month,\n  items,\n  reading\n}": NOW_QUERYResult;
    "*[_id == \"singleton-uses\"][0] {\n  categories\n}": USES_QUERYResult;
    "*[_id == \"singleton-siteSettings\"][0] {\n  trustLogos[] {\n    name,\n    url,\n    \"logoAlt\": logo.alt\n  }\n}": SITE_SETTINGS_QUERYResult;
    "{\n  \"navItems\": *[_type == \"navigation\"] | order(order asc){\n    title,\n    href,\n    icon,\n    isExternal\n  },\n  \"calLink\": *[_id == \"singleton-profile\"][0].calLink\n}": DOCK_DATA_QUERYResult;
    "{\n    \"profile\": *[_id == \"singleton-profile\"][0]{\n      firstName,\n      lastName,\n      headline,\n      shortBio,\n      fullBio,\n      email,\n      phone,\n      location,\n      availability,\n      socialLinks,\n      yearsOfExperience,\n      stats\n    },\n    \"experience\": *[_type == \"experience\"] | order(startDate desc){\n      _id,\n      jobTitle,\n      company,\n      location,\n      startDate,\n      endDate,\n      current,\n      description,\n      achievements[],\n      technologies[]->{name, category}\n    },\n    \"projects\": *[_type == \"project\"] | order(order asc){\n      _id,\n      title,\n      tagline,\n      category,\n      liveUrl,\n      githubUrl,\n      technologies[]->{name, category}\n    },\n    \"skills\": *[_type == \"skill\"] | order(name asc){\n      _id,\n      name,\n      category,\n      level,\n      yearsOfExperience,\n      percentage\n    },\n    \"education\": *[_type == \"education\"] | order(endDate desc){\n      _id,\n      degree,\n      field,\n      institution,\n      location,\n      startDate,\n      endDate,\n      description,\n      gpa\n    }\n  }": CHAT_PROFILE_QUERYResult;
    "*[_id == \"singleton-profile\"][0]{\n  firstName,\n  lastName,\n  fullBio,\n  quote,\n  quoteContext,\n  yearsOfExperience,\n  stats,\n  email,\n  phone,\n  location\n}": ABOUT_QUERYResult;
    "*[_type == \"achievement\"] | order(date desc){\n  title,\n  type,\n  issuer,\n  date,\n  description,\n  image,\n  url,\n  featured,\n  order\n}": ACHIEVEMENTS_QUERYResult;
    "*[_type == \"blog\"] | order(publishedAt desc){\n  title,\n  slug,\n  excerpt,\n  category,\n  tags,\n  publishedAt,\n  readTime,\n  featuredImage\n}": BLOG_QUERYResult;
    "*[_type == \"certification\"] | order(issueDate desc){\n  name,\n  issuer,\n  issueDate,\n  expiryDate,\n  credentialId,\n  credentialUrl,\n  logo,\n  description,\n  skills[]->{name, category},\n  order\n}": CERTIFICATIONS_QUERYResult;
    "*[_id == \"singleton-profile\"][0]{\n  email,\n  phone,\n  location,\n  socialLinks,\n  calLink\n}": PROFILE_QUERYResult;
    "*[_type == \"education\"] | order(endDate desc, startDate desc){\n  institution,\n  degree,\n  fieldOfStudy,\n  startDate,\n  endDate,\n  current,\n  gpa,\n  description,\n  achievements,\n  logo,\n  website,\n  order\n}": EDUCATION_QUERYResult;
    "*[_type == \"experience\"] | order(startDate desc){\n  company,\n  position,\n  employmentType,\n  location,\n  startDate,\n  endDate,\n  current,\n  description,\n  responsibilities,\n  achievements,\n  technologies[]->{name, category},\n  companyLogo,\n  companyWebsite\n}": EXPERIENCE_QUERYResult;
    "*[_id== \"singleton-profile\"][0] {\n  firstName,\n  lastName,\n  headline,\n  headlineStaticText,\n  headlineAnimatedWords,\n  headlineAnimationDuration,\n  shortBio,\n  fullBio,\n  email,\n  phone,\n  location,\n  availability,\n  socialLinks,\n  calLink,\n  yearsOfExperience,\n  profileImage,\n  profileImages,\n}": HERO_QUERYResult;
    "*[_type == \"resume\"] | order(isActive desc, uploadDate desc)[0] {\n  _id,\n  title,\n  resumeFile,\n  version,\n  isActive,\n  uploadDate\n}": LATEST_RESUME_QUERYResult;
    "*[_type == \"project\" && featured == true] | order(order asc)[0...6]{\n  title,\n  slug,\n  tagline,\n  category,\n  liveUrl,\n  githubUrl,\n  coverImage,\n  technologies[]->{name, category, color}\n}": PROJECTS_QUERYResult;
    "*[_type == \"service\"] | order(order asc, _createdAt desc){\n  title,\n  slug,\n  icon,\n  shortDescription,\n  fullDescription,\n  features,\n  technologies[]->{name, category},\n  deliverables,\n  pricing,\n  timeline,\n  featured,\n  order\n}": SERVICES_QUERYResult;
    "*[_type == \"skill\"] | order(category asc, order asc){\n  name,\n  category,\n  proficiency,\n  color\n}": SKILLS_QUERYResult;
    "*[_type == \"testimonial\" && featured == true] | order(order asc){\n  name,\n  position,\n  company,\n  testimonial,\n  rating,\n  date,\n  avatar,\n  companyLogo,\n  linkedinUrl\n}": TESTIMONIALS_QUERYResult;
  }
}
